# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-SVGTTGraph
version:      0.011
version_from: lib/Catalyst/View/SVGTTGraph.pm
installdirs:  site
requires:
    Catalyst:                      5.57
    SVG::TT::Graph:                0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
